CONSTITUENCIES = {
    'Chibombo': ['Chibombo Central', 'Kapiri Mposhi East', 'Kapiri Mposhi West'],
    'Kabwe': ['Bwacha', 'Kabwe Central', 'Kabwe North', 'Kabwe South', 'Makeni'],
    'Kapiri Mposhi': ['Chisamba', 'Kapiri Mposhi'],
    'Mkushi': ['Katuba', 'Mkushi North', 'Mkushi South', 'Mumbwa'],
    'Mumbwa': ['Itezhi Tezhi', 'Mumbwa', 'Namwala'],
    'Serenje': ['Chitambo', 'Serenje'],
    'Chililabombwe': ['Chingola Central', 'Kampamba', 'Lubengele', 'Lulamba', 'Lumwana', 'Mambilima', 'Musenga'],
    'Chingola': ['Buntungwa', 'Chikola', 'Kasompe', 'Lulumbula', 'Nchanga', 'Nchanga South', 'Nsobo', 'Tuntulu'],
    'Kalulushi': ['Buntungwa', 'Kantanshi', 'Kashitu', 'Kashoka', 'Muntipa', 'Nkana', 'Wusakile'],
    'Kitwe': ['Buchichi', 'Bulangililo', 'Chamboli', 'Chimwemwe', 'Chisokone', 'Garden', 'Kamfinsa', 'Kamitondo',
              'Mindolo', 'Ndeke', 'Parklands', 'Riverside'],
    'Luanshya': ['Fisenge', 'Kabundi', 'Kafubu', 'Kamakonde', 'Kantanshi', 'Mikomfwa', 'Mpatamatu', 'Roan'],
    'Lufwanyama': ['Chifubu', 'Kakoma', 'Kamfwesa', 'Kampumbu', 'Kapisha', 'Lufwanyama', 'Lumwana East', 'Lumwana West',
                   'Nkana East', 'Sofa'],
    'Masaiti': ['Chambishi', 'Chibuluma', 'Chichele', 'Chiwala', 'Kafulafuta', 'Masaiti', 'Mpongwe', 'Nsansa'],
    'Mpongwe': ['Fisengele', 'Kapiri', 'Mumbwa Chilumba', 'Nsenga', 'Tribal Authority'],
    'Mufulira': ['Bwana Mkubwa', 'Chifubu', 'Chikozya', 'Kantanshi', 'Kashinakazembe', 'Mupambe', 'Mushitala', 'Ndeke',
                 'Shinde', 'Tutwa'],
    'Ndola': ['Chifubu', 'Chimwemwe', 'Kabwe', 'Kafubu', 'Lubuto', 'Masala', 'Mukobeko', 'Nkwazi', 'Pamodzi', 'Tugela',
              'Twapia'],
    'Chadiza': ['Chadiza', 'Kazembe', 'Mwanya'],
    'Chama': ['Chama North', 'Chama South', 'Lumezi'],
    'Chipata': ['Chadiza', 'Chanjuzi', 'Chikuwe', 'Chipangali', 'Jumbe', 'Kapata', 'Kasenengwa', 'Lutembwe', 'Lwangazi',
                'Msanzala', 'Mwale', 'Nsefu', 'Nyimba', 'Petauke Central', 'Petauke', 'Sinda'],
    'Katete': ['Chieftainess Kawaza', 'Katete Central', 'Katete East', 'Mkaika'],
    'Lundazi': ['Chikoka', 'Chiweza', 'Kasenenga', 'Kundabwika', 'Lumezi', 'Lundazi Central', 'Mwase', 'Zozwe'],
    'Mambwe': ['Chiwuyu', 'Mambwe-Lungu', 'Nsenga', 'Nyamphande'],
    'Nyimba': ['Katawa', 'Khothakota', 'Lunzi', 'Nyimba'],
    'Petauke': ['Chitambo', 'Gwembe', 'Kalindawalo', 'Katena', 'Lukusuzi', 'Lusangazi', 'Lwanya', 'Mumbwa Lutzi',
                'Nyika'],

}