WARDS = {
    'Chibolya': ['Chibolya Ward', 'Chibolya West Ward', 'Kuku Compound'],
    'Chilenje': ['Chilenje Ward', 'Chilenje South Ward', 'Chilenje North Ward', 'Chawama Ward'],
    'Chimwemwe': ['Chimwemwe Ward', 'Helen Kaunda Ward', 'Kanyama Ward'],
    'Chudleigh': ['Chudleigh Ward', 'Munali Ward'],
    'Garden': ['Garden Ward', 'Woodlands Ward'],
    'George': ['George Ward', 'Kalingalinga Ward'],
    'Golf': ['Golf Club Ward', 'Matero Ward'],
    'Itawa': ['Itawa Ward', 'Lilanda Ward'],
    'John Howard': ['John Howard Ward', 'Makululu Ward'],
    'Kabulonga': ['Kabulonga Ward', 'Ibex Hill Ward', 'Kamwala Ward', 'Roma Ward'],
    'Kalingalinga': ['Kalingalinga Ward', "Ng'ombe Ward"],
    'Kamanga': ['Kamanga Ward', 'Ridge Way Ward'],
    'Kuku': ['Kuku Compound'],
    'Makeni': ['Makeni Ward', 'Meanwood Ward', 'Ndeke Village Ward'],
    'Malambo': ['Malambo Ward', 'Mtendere Ward', 'Misisi Ward'],
    'Mandevu': ['Mandevu Ward', 'Matero Ward', 'Mumbwa Road Ward'],
    'Matero': ['Matero Ward'],
    'Munali': ['Munali Ward', 'Vorna Valley Ward'],
    'Ngwerere': ['Ngwerere Ward', 'Chelstone Ward', 'Chibelo Ward'],
    'Northmead': ['Northmead Ward', 'Kabulonga Ward', 'Long Acres Ward'],
    'Nyumba Yanga': ['Nyumba Yanga Ward', 'Ridgeway Ward'],
    'Olympia': ['Olympia Park Ward', 'Olympia Extension Ward', 'Chilenje Ward'],
    'Pamodzi': ['Pamodzi Ward', 'Kabulonga Ward'],
    'Roma': ['Roma Ward', 'Salama Park Ward'],
    'Sosongo': ['Sosongo Ward', 'Lusaka East Ward'],
    'Thorn Park': ['Thorn Park Ward', 'Chelston Ward', 'Kabulonga Ward'],
    'Woodlands': ['Woodlands Ward']
}
